# Generated by Django 6.1.1 on 2026-10-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_url_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
